create table sensor(
  id int4 generated by default as identity primary key,
  name varchar(100)
);

create table measurement(
    id int4 generated by default as identity,
    sensor_id int4 references sensor (id),
    value float,
    raining bool
);